# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='org_id',
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackers.Hacker'),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AlterField(
            model_name='hack',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackers.Hacker'),
        ),
        migrations.DeleteModel(
            name='Hacker',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
