# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0003_auto_20160607_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hack',
            name='pub_date',
        ),
    ]
